### ISSUE TITLE
[BUG] Fix %healthplayer% and other placeholder names sometimes showing on hud

### ISSUE THREAD

**Issue by Blueberryy** [CriticalFlaw/TF2HUD.Fixes#73]
**Issue**
When you look at the team mate you see placeholder for a moment where his number of health must be.

**Comment by CriticalFlaw** [comment]
afaik this was fixes code side, not in the hud files.

Ref: https://github.com/Hypnootize/TF2-Default-HUD/commits/master

**Comment by Blueberryy** [comment]
> afaik this was fixes code side, not in the hud files.
> 
> Ref: https://github.com/Hypnootize/TF2-Default-HUD/commits/master

but i see %health% when i look at my team member for a moment and i can't see that on regular hud

**Comment by CriticalFlaw** [comment]
I don't believe that it was fixed in the original hud files because then it would have been shown in the tracker.

**Comment by Maurvick** [comment]
It is code side fix, so it's can't be ported to community fixes, but I noticed that some placeholder still showing up.

**Comment by Blueberryy** [comment]
alright. i guess i will have to rename the issue

**Comment by Maurvick** [comment]
@Blueberryy It's code side thing, custom hud CAN'T fix this, it's more likely game can't load quickly HUD files and show placeholders.

**Comment by Blueberryy** [comment]
> @Blueberryy Custom hud CAN'T fix this, it's more likely game can't load quickly HUD files and show placeholders.

i haven't tested it with available for hud modification files but i will investigate and try to fix that before i close this issue

**Comment by CriticalFlaw** [comment]
Any update @Blueberryy ?

**Comment by Maurvick** [comment]
I think we should close this issue.

**Comment by Blueberryy** [comment]
yeah i will close it for now until i find anything about fix
